[package]
name = "r2d2_mysql"
version = "3.0.0"
authors = ["outersky <outersky@gmail.com>"]
license = "MIT"
documentation = "http://outersky.github.io/r2d2-mysql/doc/v0.2.0/r2d2_mysql"
description = "MySQL support for the r2d2 connection pool"
repository = "https://github.com/outersky/r2d2-mysql"
keywords = ["mysql", "sql", "pool", "database","r2d2"]

[lib]
name = "r2d2_mysql"
path = "src/lib.rs"

[dependencies]
rustc-serialize = "~0.3.19"
r2d2 = "0.7.0"

[dependencies.mysql]
mysql = "7.1.2"
default-features = false
