[package]
name = "r2d2_mysql"
version = "0.2.0"
authors = ["outersky <outersky@gmail.com>"]
license = "MIT"
documentation = "http://outersky.github.io/r2d2-mysql/doc/v0.2.0/r2d2_mysql"
description = "MySQL support for the r2d2 connection pool"
repository = "https://github.com/outersky/r2d2-mysql"
keywords = ["mysql", "sql", "pool", "database","r2d2"]

[lib]
name = "r2d2_mysql"
path = "src/lib.rs"

[dependencies]
rustc-serialize = "0.3"
r2d2 = "0.6"

[dependencies.mysql]
version = "0.16.0"
default-features = false


