name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - { name: msrv, version: 1.70.0 }
          - { name: stable, version: stable }
          - { name: nightly, version: nightly }

    name: tests / ${{ matrix.version.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust (${{ matrix.version.name }})
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: ${{ matrix.version.version }}

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: 'ci'
          mysql password: 'ci'

      - run: cargo test
        env:
          DATABASE_URL: mysql://ci:ci@127.0.0.1:3306
